In [1]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Reshape, Lambda
import tensorflow as tf
import numpy as np
import csv

2024-04-01 18:10:54.058328: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-01 18:10:54.737011: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [30]:
x = []
y = []

with open("data_new.csv", "r") as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=",")
    convert_rgb = lambda color: tuple(int(color[i:i+2], 16) for i in (0,2,4))
    for row in csv_reader:
        x.append(convert_rgb(row[0]))
        y.append([convert_rgb(x) for x in row[1].split(" ")])

train_x = np.array(x) / 255
train_y = np.array(y) / 255

In [31]:
model = Sequential([
    Dense(128, input_shape=(3,), activation='relu'),
    Dense(256, activation='relu'),
    Dense(512, activation='relu'),
    Dense(1024, activation='relu'),
    Dense(2048, activation='relu'),
    Dense(9, activation='linear'),  # Output layer for 3 RGB tuples
    Reshape((3, 3))  # Reshaping to match the (3, 3) output shape
])

In [32]:
model.compile(optimizer='adam', loss='mse')

In [33]:
#If getting libdevice error, just sleep and then run again.
model.fit(train_x, train_y, epochs=50)

Epoch 1/50
100/100 [==============================] - 3s 19ms/step - loss: 0.0903
Epoch 2/50
100/100 [==============================] - 2s 18ms/step - loss: 0.0696
Epoch 3/50
100/100 [==============================] - 2s 18ms/step - loss: 0.0695
Epoch 4/50
100/100 [==============================] - 2s 18ms/step - loss: 0.0697
Epoch 5/50
100/100 [==============================] - 2s 18ms/step - loss: 0.0684
Epoch 6/50
100/100 [==============================] - 2s 18ms/step - loss: 0.0681
Epoch 7/50
100/100 [==============================] - 2s 18ms/step - loss: 0.0673
Epoch 8/50
100/100 [==============================] - 2s 18ms/step - loss: 0.0676
Epoch 9/50
100/100 [==============================] - 2s 18ms/step - loss: 0.0668
Epoch 10/50
100/100 [==============================] - 2s 18ms/step - loss: 0.0665
Epoch 11/50
100/100 [==============================] - 2s 18ms/step - loss: 0.0668
Epoch 12/50
100/100 [==============================] - 2s 18ms/step - loss: 0.0666
Epoch 13/50
1

In [34]:
# Assuming you have test data
test_data = np.array([(23, 68, 45)])  # Example test RGB tuples

# Use the trained model to make predictions
predictions = model.predict(test_data)
predictions = np.round(predictions)

print(predictions)

1/1 [==============================] - 0s 69ms/step
[[[ 5. 69. 66.]
  [50. 69. 81.]
  [83. 41. 88.]]]


In [35]:
print(predictions[0][0])
print(predictions[0][1])
print(predictions[0][2])

[ 5. 69. 66.]
[50. 69. 81.]
[83. 41. 88.]
