In [1]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Reshape, Lambda
import tensorflow as tf
import numpy as np
import csv

2024-05-31 01:49:02.595608: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-31 01:49:03.375566: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
x = []
y = []

with open("data_new.csv", "r") as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=",")
    convert_rgb = lambda color: tuple(int(color[i:i+2], 16) for i in (0,2,4))
    for row in csv_reader:
        x.append(convert_rgb(row[0]))
        y.append([convert_rgb(x) for x in row[1].split(" ")])

train_x = np.array(x) / 255
train_y = np.array(y) / 255

In [3]:
model = Sequential([
    Dense(128, input_shape=(3,), activation='relu'),
    Dense(256, activation='relu'),
    Dense(512, activation='relu'),
    Dense(1024, activation='relu'),
    Dense(2048, activation='relu'),
    Dense(9, activation='linear'),  # Output layer for 3 RGB tuples
    Reshape((3, 3))  # Reshaping to match the (3, 3) output shape
])

/home/pavle/.local/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
2024-05-31 01:49:04.510561: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-05-31 01:49:04.546364: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L

In [4]:
model.compile(optimizer='adam', loss='mse')

In [5]:
#If getting libdevice error, just sleep and then run again.
model.fit(train_x, train_y, epochs=50)

Epoch 1/50


I0000 00:00:1717112946.037502    5846 service.cc:145] XLA service 0x71660c002660 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1717112946.037523    5846 service.cc:153]   StreamExecutor device (0): NVIDIA GeForce GTX 1650 Ti with Max-Q Design, Compute Capability 7.5
2024-05-31 01:49:06.072553: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2024-05-31 01:49:06.243352: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:465] Loaded cuDNN version 8907


 74/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1445

I0000 00:00:1717112947.821162    5846 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


104/104 ━━━━━━━━━━━━━━━━━━━━ 9s 59ms/step - loss: 0.1283
Epoch 2/50
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0699
Epoch 3/50
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0684
Epoch 4/50
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0681
Epoch 5/50
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0652
Epoch 6/50
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0680
Epoch 7/50
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0651
Epoch 8/50
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0660
Epoch 9/50
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0647
Epoch 10/50
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0647
Epoch 11/50
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0636
Epoch 12/50
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0650
Epoch 13/50
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0646
Epoch 14/50
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0635
Epoch 15/50
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0635

In [6]:
# Assuming you have test data
test_data = np.array([(23, 68, 45)])  # Example test RGB tuples

# Use the trained model to make predictions
predictions = model.predict(test_data)
predictions = np.round(predictions)

print(predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 183ms/step
[[[  9.  89.  20.]
  [-17.  83.  87.]
  [ 33.  83.  90.]]]


In [7]:
print(predictions[0][0])
print(predictions[0][1])
print(predictions[0][2])

[ 9. 89. 20.]
[-17.  83.  87.]
[33. 83. 90.]
